### ISSUE TITLE
FAILED - RETRYING: Wait until keycloak becomes active http://localhost:8080/realms/master/.well-known/openid-configuration (4 retries left)

### ISSUE THREAD

**Issue by ayoubch11** [ansible-middleware/keycloak#101]
##### SUMMARY
After deploying the keycloak_quarkus role, I enabled the "keycloak_quarkus_https_enabled: True" option and generated a certificate for HTTPS usage. i have a problem ERROR: /opt/keycloak/keycloak-22.0.0/conf/tls.crt
can you please help me 
[log_keycloak.log](https://github.com/ansible-middleware/keycloak/files/12073573/log_keycloak.log)

**Comment by guidograzioli** [comment]
Hello, for tls/https to work you need two files, one with the key and one with the certificate, set in the following variables:
```
keycloak_quarkus_key_file: "{{ keycloak.home }}/conf/server.key.pem"
keycloak_quarkus_cert_file: "{{ keycloak.home }}/conf/server.crt.pem"
```
