### ISSUE TITLE
Support for debian/ubuntu os

### ISSUE THREAD

**Issue by gionn** [ansible-middleware/keycloak#123]
##### SUMMARY

Currently the available roles only supports RHEL and derivatives, but it should not hard to support also debian derivates still leveraging systemd.

(currently not high priority for us but can be in the next future)

##### ISSUE TYPE
 - Feature Idea

**Comment by guidograzioli** [comment]
We already have [this](https://github.com/ansible-middleware/keycloak/blob/main/roles/keycloak_realm/meta/main.yml#L13)  ; however adding a precondition check won't hurt I guess. 

debian/ubuntu is not in my roadmap, but of course contributions are more than welcome!

**Comment by gionn** [comment]
Thanks @guidograzioli!
