### ISSUE TITLE
Request for New Release

### ISSUE THREAD

**Issue by Footur** [ansible-middleware/keycloak#130]
Our team has been eagerly awaiting the latest features and bug fixes to be merged into the main branch. However, the latest release is out of date and we are currently unable to benefit from the improvements made to the codebase. To ensure that we can use the latest version in our production environment, we respectfully request a new release.

**Comment by guidograzioli** [comment]
I am running some more testing downstream, however it will happen today or at the latest tomorrow. Sorry it has been taking long but we had a few breaking changes to handle.
