### ISSUE TITLE
Health check broken in 2.0.0 due to incorrect health_url

### ISSUE THREAD

**Issue by jonathanspw** [ansible-middleware/keycloak#136]
##### SUMMARY
The health check in keycloak_qurkus fails to properly detect if a keycloak instance is online.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible [core 2.16.0]
  config file = /home/jonathan/alma-ansible/ansible-keycloak/ansible.cfg
  configured module search path = ['/home/jonathan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/jonathan/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.0 (main, Oct  2 2023, 00:00:00) [GCC 13.2.1 20230918 (Red Hat 13.2.1-3)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
middleware_automation.keycloak 2.0.0
```

##### STEPS TO REPRODUCE
Run a playbook with keycloak_quarkus.

##### EXPECTED RESULTS
The playbook should recognize that the server is online.

##### ACTUAL RESULTS
The check loops due to a missing `/` after the port in the URL.  This stems from a missing `/` in https://github.com/ansible-middleware/keycloak/blob/main/roles/keycloak_quarkus/vars/main.yml#L7

**Comment by guidograzioli** [comment]
Hello, thanks for the issue and PR; however, the health url is properly concatenated, the failures are due to the keycloak ver 23 update (since 23 keycloak.conf need lowercase booleans, where instead the template would emit True/False strings)
