### ISSUE TITLE
keycloak_quarkus: `rhbk_apply_patches` not referenced anywhere

### ISSUE THREAD

**Issue by hwo-wd** [ansible-middleware/keycloak#155]
##### SUMMARY
<title>

##### ISSUE TYPE
 - Bug Report (or a feature request ;-))
 
 @guidograzioli do you happen to know how rhbk patches will happen? I mean, there was a `22.0.6` and the upgrade to `22.0.7` happened via changing the version mnemonicer, but the question is, whether incremental patches are available or simple a installation from scratch?
 
 Thanks!

**Comment by guidograzioli** [comment]
The feature along with the variable was migrated from the sso collection (with rhsso having incremental patches). Currently, there seem to be full releases for patch versions, but until I am sure about it I'd keep the parameter.
