### ISSUE TITLE
keycloak_quarkus: Infinispan settings

### ISSUE THREAD

**Issue by hwo-wd** [ansible-middleware/keycloak#156]
So I've been experiencing weird RHBK behavior which, after some trial and error, could only really stem from Infinispan.
Checking the configuration I've noticed that:
* keycloak <v22[^1] used Quarkus <v3, where using `quarkus.infinispan-client.server-list` in the `quarkus.properties` file was [just fine](https://quarkus.io/version/2.13/guides/all-config#quarkus-infinispan-client_quarkus.infinispan-client.server-list), however:
* keycloak >= v22, and thus RHBK, upgraded to Quarkus v3 (`3.2.6` in case of RHBK) said setting is no more, since it has been replaced by [`quarkus.infinispan-client.hosts`](https://quarkus.io/version/3.2/guides/all-config#quarkus-infinispan-client_quarkus.infinispan-client.hosts)

@guidograzioli I presume you want to be compatible with Keycloak <v22, right?
Meanwhile, I'll start to work on a fix 

[^1]: <https://www.keycloak.org/docs/latest/release_notes/#upgrade-to-quarkus-3-x>

**Comment by guidograzioli** [comment]
Seems similar to #146

**Comment by hwo-wd** [comment]
> Actually the next work in the roadmap, is to provide integration between rhbk and datagrid in preparation of active/active ha; 

so basically templating `cache-ispn.xml` and checking whether `keycloak_quarkus_ha_enabled` is set and if so, set the tcpping hosts according to the current inventory, correct?
Is this WIP already, or is it "planned"? cause it's pretty much the next thing on my roadmap (albeit, w/o external dg)

**Comment by guidograzioli** [comment]
It's not started; on legacy keycloak we had JDBC_PING as default discovery, but I'd switch to TCPPING and initial hosts because it is more reliable. If you wish to start on keyclock with embedded infinispan you are welcome since my work will focus on having infinispan external, in preparation of active/active setups.

**Comment by hwo-wd** [comment]
I'll work on TCPPING, shouldn't be hard; anyway,  #157 tests look ok, so we can let this go into main
