### ISSUE TITLE
Vault support

### ISSUE THREAD

**Issue by aph3rson** [ansible-middleware/keycloak#172]
##### SUMMARY

Keycloak has support for a [Vault SPI](https://www.keycloak.org/server/vault). Two providers are available by default in Keycloak, including a file and JKS provider.

These have to be added at build time, with the `--vault=file` or `--vault=keystore` args.

It would be nice if this module supported said functionality.

##### ISSUE TYPE
 - Feature Idea

**Comment by guidograzioli** [comment]
I think the only useful implementation of vaults in the ansible context is with keystores; I'll proceed with that and only do plain-text file directory if requested
