### ISSUE TITLE
keycloak_realm role requires realm defined in multiple places

### ISSUE THREAD

**Issue by aph3rson** [ansible-middleware/keycloak#179]
##### SUMMARY
https://github.com/ansible-middleware/keycloak/blob/7a0a99a31c2fcd0e218d415cda5613de4d47be1e/roles/keycloak_realm/tasks/main.yml#L44

Here, individuals using the `keycloak_realm` role will need to define the realm name in two places: the outer role args, and the inner part of the user federation.

This seems like it could use `item.realm or keycloak_realm` to handle most default situations.

##### ISSUE TYPE
 - Feature Idea

**Comment by guidograzioli** [comment]
Good point; I'll add the `| default(keycloak_realm)`
