### ISSUE TITLE
Support Socket Settings Customization

### ISSUE THREAD

**Issue by motaparthipavankumar** [ansible-middleware/keycloak#20]
Right now we don't have option to customize the http-listener and socket binding settings, For example to customize as below

```
...
        <subsystem xmlns="urn:jboss:domain:undertow:12.0" ...>
            ...
            <server name="default-server">
                ...
                <http-listener name="default" socket-binding="http" redirect-socket="proxy-https" proxy-address-forwarding="true"/>
                ...
...
    <socket-binding-group name="standard-sockets" default-interface="public" port-offset="${jboss.socket.binding.port-offset:0}">
        ...
        <socket-binding name="proxy-https" port="443"/>
...
```

Changes have to be made to existing two templates roles/keycloak/templates/......xml.j2, so that based on the condition consumers can opt to customize as needed.

**Comment by guidograzioli** [comment]
While not directly configurable in the default template, at least for the moment, it is possible to do arbitrary configurations via #30 
Closing for now
