### ISSUE TITLE
Allow for downloading JDBC drivers from alternate URLs and allow for using username/password

### ISSUE THREAD

**Issue by InfoSec812** [ansible-middleware/keycloak#200]
##### SUMMARY
In some environments, access to Maven Central is not allowed, but those environments often have a local repository manager which "proxies" maven central. Sometimes those repository managers require authentication to download. It would be useful to be able to:
1. Set an alternative URL for downloading JDBC drivers
2. Set credentials for authentication to download said JDBC drivers.

##### ISSUE TYPE
 - Feature Idea

**Comment by guidograzioli** [comment]
Good idea!

**Comment by guidograzioli** [comment]
We should likely do the same here https://github.com/ansible-middleware/keycloak/blob/main/roles/keycloak_quarkus/tasks/install.yml#L62
