### ISSUE TITLE
Copying Key Material

### ISSUE THREAD

**Issue by Footur** [ansible-middleware/keycloak#208]
##### SUMMARY
The default directory for certificates in `keycloak_quarkus` is `"{{ keycloak_home }}/certs"`. This directory is not created by the role. Also, I am missing a task that copies the key material to `"{{ keycloak_home }}/certs"`. This should be done before the first start of Keycloak.

##### ISSUE TYPE
 - Feature Idea

**Comment by guidograzioli** [comment]
Correct, at the moment the role expects the certificates to be already in place (ideally, one would install them under /etc/pki/tls/ ). We could have a few tasks that manage to use local files or download them and copy them to target nodes.

**Comment by Footur** [comment]
@guidograzioli What do you think about using the directories
- `/etc/pki/tls/private` for the private key and
- `/etc/pki/tls/cert` for the certificate
as default values?

**Comment by guidograzioli** [comment]
Since what you're proposing is the default in Red Hat distributions, I without any doubt second that!

**Comment by Footur** [comment]
@guidograzioli Can you create a new release please? :pray:
