### ISSUE TITLE
Service availability wait after restart not happening by default

### ISSUE THREAD

**Issue by gionn** [ansible-middleware/keycloak#233]
##### SUMMARY

Hello,

after upgrading this collection:

```
   - name: middleware_automation.keycloak
-    version: 2.1.2
+    version: 2.3.0
```

I got a failure in my playbook because I have some tasks to configure realm/clients upon the execution of this collection, because the keycloak service was (not yet) up and running upon first (re)start.

After setting `keycloak_quarkus_restart_health_check: true`, I've got the old behaviour for which the role do an active wait for the service to be available.

What's the reason for having it optional?

**Comment by guidograzioli** [comment]
A major overhaul of the HA scenario happened; I guess at some point the flag turned from always true, to true only is ha_enabled is true. See: https://github.com/ansible-middleware/keycloak/pull/231 and https://github.com/ansible-middleware/keycloak/pull/199

Totally open for discussing flicking it back to always true

**Comment by gionn** [comment]
I took a quick look and seems safe to switch the default to true, raised a PR

**Comment by guidograzioli** [comment]
I'll bump to 2.4.0 and release as soon the CI finishes
